#!/system/bin/sh
VOLT_TABLE="$1"
VOLT_TABLE_RAW=`cat $VOLT_TABLE`;
arrvolt=(`echo ${VOLT_TABLE_RAW}`);
count=0;
count2=1;
if [[ ! -z $2 ]];then
	if [[ ! -z $3 ]];then
		echo "$2 $3" > $VOLT_TABLE;
	fi
	for i in "${arrvolt[@]}"
	do
		let count2=count2+1;
		if [ $count2 -eq 2 ];then
			let count2=0;
			if [ $i == $2 ];then
				echo ${arrvolt[`expr $count + 1`]}
				break
			fi
		fi
		let count=count+1;
	done
fi
