#!/system/bin/sh
VOLT_TABLE="/sys/devices/platform/mali_dev.0/volt_table"
VOLT_TABLE_RAW=`cat $VOLT_TABLE`;
arrvolt=(`echo ${VOLT_TABLE_RAW}`);
count=0;
count2=1;
if [[ ! -z $1 ]];then
	if [[ ! -z $2 ]];then
		echo "$1 $2" > $VOLT_TABLE;
	fi
	for i in "${arrvolt[@]}"
	do
		let count2=count2+1;
		if [ $count2 -eq 2 ];then
			let count2=0;
			if [ $i == $1 ];then
				echo ${arrvolt[`/res/busybox expr $count + 1`]}
				break
			fi
		fi
		let count=count+1;
	done
fi
